# Generated by Django 5.2.4 on 2025-08-12 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='chat_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='chatbot.chatmessage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='search_query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='chatbot.searchquery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='chat_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot.chatmessage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userfeedback',
            unique_together={('chat_message', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_session', 'created_at'], name='chatbot_cha_chat_se_b9c3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_type', 'message_type'], name='chatbot_cha_sender__a911c4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['intent_detected'], name='chatbot_cha_intent__4a1cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='chatbot_cha_session_9384e5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'status'], name='chatbot_cha_user_id_129580_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['last_activity'], name='chatbot_cha_last_ac_54a63f_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['search_type', 'created_at'], name='chatbot_sea_search__bde0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['source_used'], name='chatbot_sea_source__a32644_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['search_query', 'position'], name='chatbot_sea_search__2e76d2_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['result_type'], name='chatbot_sea_result__a5d9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['relevance_score'], name='chatbot_sea_relevan_98b173_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['feedback_type', 'created_at'], name='chatbot_use_feedbac_fff2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['rating'], name='chatbot_use_rating_80f06e_idx'),
        ),
    ]
