# Generated by Django 5.2.4 on 2025-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='new',
            field=models.CharField(blank=True, null=True),
        ),
    ]
