# Generated by Django 5.2.4 on 2025-08-01 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatmessage_audio_file_chatmessage_image_analysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSourceCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50, unique=True)),
                ('api_key', models.TextField(blank=True)),
                ('api_secret', models.TextField(blank=True)),
                ('base_url', models.URLField()),
                ('rate_limit_per_hour', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'External Source Credentials',
            },
        ),
        migrations.CreateModel(
            name='PopularSearchTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=200, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('success_rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField()),
                ('search_type', models.CharField(choices=[('text', 'Text Search'), ('voice', 'Voice Search'), ('image', 'Image Search')], default='text', max_length=20)),
                ('found_results', models.BooleanField(default=False)),
                ('result_source', models.CharField(choices=[('finda_db', 'Finda Database'), ('amazon', 'Amazon'), ('jumia', 'Jumia'), ('konga', 'Konga'), ('other', 'Other External Source'), ('none', 'No Results Found')], default='none', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_external_sources', models.JSONField(default=list, help_text="List of preferred external sources like ['amazon', 'jumia', 'konga']")),
                ('price_range_preference', models.CharField(choices=[('budget', 'Budget-friendly'), ('mid', 'Mid-range'), ('premium', 'Premium'), ('any', 'Any price range')], default='any', max_length=20)),
                ('location_preference', models.CharField(default='Nigeria', max_length=100)),
                ('include_similar_items', models.BooleanField(default=True)),
                ('show_external_alternatives', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='external_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='found_in_database',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='product_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='product_rating',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='search_terms_used',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uservoicesettings',
            name='include_audio_summaries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uservoicesettings',
            name='preferred_response_length',
            field=models.CharField(choices=[('brief', 'Brief (20-30 words)'), ('standard', 'Standard (30-40 words)'), ('detailed', 'Detailed (40-50 words)')], default='standard', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'timestamp'], name='chatbot_cha_user_id_ac2c89_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['found_in_database'], name='chatbot_cha_found_i_a9c4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['external_source'], name='chatbot_cha_externa_3ad4df_idx'),
        ),
        migrations.AddIndex(
            model_name='popularsearchterms',
            index=models.Index(fields=['search_count'], name='chatbot_pop_search__a86c35_idx'),
        ),
        migrations.AddIndex(
            model_name='popularsearchterms',
            index=models.Index(fields=['last_searched'], name='chatbot_pop_last_se_2927d5_idx'),
        ),
        migrations.AddField(
            model_name='searchanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finda_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['search_type', 'timestamp'], name='chatbot_sea_search__774b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['result_source'], name='chatbot_sea_result__cd30c1_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['found_results'], name='chatbot_sea_found_r_aad77b_idx'),
        ),
    ]
