# Generated by Django 5.2.4 on 2025-08-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_externalsourcecredentials_popularsearchterms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalSourceCredentials',
        ),
        migrations.DeleteModel(
            name='PopularSearchTerms',
        ),
        migrations.RemoveField(
            model_name='searchanalytics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chatbot_cha_user_id_ac2c89_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chatbot_cha_found_i_a9c4f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chatbot_cha_externa_3ad4df_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='external_source',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='found_in_database',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='product_rating',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='search_terms_used',
        ),
        migrations.RemoveField(
            model_name='uservoicesettings',
            name='include_audio_summaries',
        ),
        migrations.RemoveField(
            model_name='uservoicesettings',
            name='preferred_response_length',
        ),
        migrations.DeleteModel(
            name='SearchAnalytics',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
