# Generated by Django 5.2.4 on 2025-08-12 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='main.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.state'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_ratings', to='main.services'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='main.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.services'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='servicerating',
            unique_together={('service', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'product'), ('user', 'service')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type', 'is_active'], name='main_catego_categor_ac0646_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='main_catego_parent__476ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='main_catego_is_feat_d738ed_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'is_active'], name='main_city_state_i_759c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'is_major_city'], name='main_city_country_4d673d_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_capital'], name='main_city_is_capi_5ea2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['product', 'is_active'], name='main_produc_product_7a6795_idx'),
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['rating'], name='main_produc_rating_d8489b_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['product_status', 'is_promoted', 'is_featured'], name='main_produc_product_d75ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category', 'country', 'state', 'city'], name='main_produc_categor_4bd673_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['created_at'], name='main_produc_created_ba71e9_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['slug'], name='main_produc_slug_06cc20_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['user', 'product_status'], name='main_produc_user_id_9c352a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['search_term', 'created_at'], name='main_search_search__4e3a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['country', 'state', 'city'], name='main_search_country_65e07e_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'created_at'], name='main_search_user_id_347b57_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerating',
            index=models.Index(fields=['service', 'is_active'], name='main_servic_service_bebeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerating',
            index=models.Index(fields=['rating'], name='main_servic_rating_289e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['service_status', 'is_promoted', 'is_featured'], name='main_servic_service_964249_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['category', 'country', 'state', 'city'], name='main_servic_categor_40919a_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['created_at'], name='main_servic_created_89b588_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['slug'], name='main_servic_slug_74338c_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['user', 'service_status'], name='main_servic_user_id_8a1942_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'is_active'], name='main_state_country_3444c5_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['code'], name='main_state_code_a145ea_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'created_at'], name='main_userfa_user_id_e809fd_idx'),
        ),
    ]
